---
title: "Untitled"
author: "Caitie"
date: "08/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(tmap)
library(sf)
library(patchwork)
#library(rnaturalearth)
#library(rnaturalearthdata)
library(viridis)
library(countrycode)

t_crs<-'ESRI:54009'

```

# Load data

Number of countries per basin
```{r}
list_prop_basin<-list.files(here("output_data"), pattern = "Prop_basin_iso3", full.names = TRUE)

sub_prop_basin<-list_prop_basin[grep(list_prop_basin, pattern = ".csv")] 

dat <- 
  do.call(rbind,
          lapply(sub_prop_basin, read.csv))

```

```{r}
#Count number of countries in each watershed
iso3_basins<-dat %>% 
  group_by(MAIN_BAS) %>% 
  summarise(n_iso3 = length(unique(ISO3))) 

trans_iso3_basins<-iso3_basins %>% 
  filter(n_iso3>1)
```
# Country radial chart

```{r}
iso3_cont_basins<-dat %>% 
  #filter(!duplicated(MAIN_BAS)) %>% 
  group_by(ISO3, Continent) %>% 
  summarise(n_basins = length(unique(MAIN_BAS)))

trans_basins<-dat %>% 
  filter(n >1)

iso3_trans_basins<-dat %>% 
  filter(MAIN_BAS %in% trans_basins$MAIN_BAS) %>% 
       #  !duplicated(MAIN_BAS)) %>% 
  group_by(ISO3, Continent) %>% 
  summarise(n_trans = length(unique(MAIN_BAS)))

iso3_df<-full_join(iso3_cont_basins, iso3_trans_basins) %>% 
  mutate(prop_trans = n_trans/n_basins)
```

```{r}
#list_crypt_sed_basin<-list.files(here("output_data/Transboundary"), pattern = #"Terrestrial_transboundary_", full.names = TRUE)

#crypt_sed_dat <- 
#  do.call(rbind,
#          lapply(list_crypt_sed_basin, read.csv)) %>% 
#  filter(ENDORHE == 1,
#         n_iso3 >1)

#trans_crypt_sed_sum<-crypt_sed_dat %>% 
#  group_by(ISO3, Continent, MAIN_BAS) %>% 
#  filter(!duplicated(MAIN_BAS))
```

```{r}
pp_loc_list<-list.files(here("output_data/Pourpoints"), pattern = "Missing_pp_chunk", full.names = T)

pp_loc_mis<-
  do.call(rbind,
          lapply(pp_loc_list, read.csv))

pp_all<-read.csv(here("output_data/Pourpoints/PP_location_all.csv"))

pp_done<-rbind(pp_all, pp_loc_mis) %>% 
  dplyr::select(HYRIV_I, NEXT_DO, MAIN_RI, rv_d_3_, ENDORHE, MAIN_BAS)

```

```{r}
list_sed_basin<-list.files(here("output_data/Sediment"), pattern = ".shp", full.names = T)

#list_sed_basin<-list.files(here("output_data/Transboundary"), pattern = #"Terrestrial_transboundary_", full.names = TRUE)

sed_dat <- 
  do.call(rbind,
          lapply(list_sed_basin, st_read)) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry)
```

```{r}
crypt<-left_join(sed_dat, pp_done, by = "MAIN_BAS") %>% 
  filter(ENDORHE == 0)

length(unique(crypt$MAIN_BAS))/23934
```

```{r}
trans_crypt<-crypt %>% 
  filter(MAIN_BAS %in% trans_basins$MAIN_BAS)

length(unique(trans_crypt$MAIN_BAS))
length(unique(trans_crypt$MAIN_BAS))/length(unique(trans_basins$MAIN_BAS))
```

```{r}
iso3_crypt_trans_basins<- trans_crypt %>% 
  #filter(!duplicated(MAIN_BAS)) %>% 
  group_by(ISO3, Continent) %>% 
  summarise(n_crypt_basins = length(unique(MAIN_BAS)))

#iso3_df<-full_join(iso3_cont_basins, iso3_trans_basins) %>%
#  full_join(., iso3_crypt_trans_basins) %>% 
#  mutate(n_single = n_basins - n_trans) %>% 
#  dplyr::select(-n_basins) %>% 
#  pivot_longer(., cols = c(n_single, n_trans, n_crypt_basins), names_to = #"type", values_to = "n") %>% 
#  mutate(labels = ifelse(type == "n_single","Single", 
#                         ifelse(type == "n_trans", "Transboundary", #"Trans-cryptorheic"))) %>% 
#  ungroup()


#%>% 
#  mutate(prop_trans = n_trans/n_basins,
#         prop_crypt = n_crypt_basins/n_basins,
#         prop_trans_crypt = n_crypt_basins/n_trans)
```

```{r}
# Create dataset

join_df<-full_join(iso3_df, iso3_crypt_trans_basins)

data<-join_df %>% 
  #filter(labels == "Transboundary") #%>% 
  mutate(Country = countrycode(ISO3, "iso3c", "country.name"),
        perc_trans = prop_trans*100,
        perc_crypt_trans = (n_crypt_basins/n_trans)*100,
        perc_crypt_trans = ifelse(is.na(perc_crypt_trans) == T, 0, perc_crypt_trans),
        Country = ifelse(Country == "Micronesia (Federated States of)", "Micronesia", Country)) %>% 
  rename(group = Continent,
         individual = Country,
         value = perc_trans,
         fill_val = perc_crypt_trans) %>% 
  dplyr::select(-n_basins, -n_trans, -prop_trans, -ISO3)

data<- data %>% arrange(group,value)

# Set a number of 'empty bar' to add at the end of each group
empty_bar=3
to_add = data.frame( matrix(NA, empty_bar*length(unique(data$group)), ncol(data)) )
colnames(to_add) = colnames(data)
to_add$group=rep(levels(data$group), each=empty_bar)
data=rbind(data, to_add) 
data=data %>% arrange(group)
data$id=seq(1, nrow(data))
 
# Get the name and the y position of each label
label_data=data
number_of_bar=nrow(label_data)
angle= 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust<-ifelse( angle < -90, 1, 0)
label_data$angle<-ifelse(angle < -90, angle+180, angle)
 
# prepare a data frame for base lines
base_data=data %>% 
  filter(!is.na(group) == T) %>% 
  group_by(group) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)),
         group = ifelse(group == "North America","North \nAmerica",
                        ifelse(group == "South America", "South \nAmerica", group))) 
 
# prepare a data frame for grid (scales)
grid_data = base_data
grid_data$end = grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start = grid_data$start - 1
grid_data=grid_data[-1,]
 

```

```{r}
# Make the plot
p = ggplot(data, aes(x=as.factor(id), y=value, fill = fill_val)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  geom_bar(aes(x=as.factor(id), y=value, fill = fill_val), stat="identity", alpha=0.5) +
   scale_fill_continuous(low="blue", high="red", limits=c(0,100)) +
  
  
  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
  # Add text showing the value of each 100/75/50/25 lines
  annotate("text", x = rep(max(data$id),5), y = c(20, 40, 60, 80, 100), label = c("20", "40", "60", "80", "100") , color="grey", size=3 , angle=0, fontface="bold", hjust=1) +
  
  geom_bar(aes(x=as.factor(id), y=value, fill=fill_val), stat="identity", alpha=0.5) +
  ylim(-100,120) +
  theme_minimal() +
  theme(
    #legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  labs(fill = "Transboundary\ncryptorheic (%)") +
  coord_polar() + 
  geom_text(data=label_data, aes(x=id, y=value+5, label=individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) +
  
  # Add base line information
  geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
  geom_text(data=base_data, aes(x = title, y = -18, label=group), hjust=c(0.5,0.5,0.2,0.2,0.2,0), vjust = c(0,0,0,0,0,0),colour = "black", alpha=0.8, size=3, fontface="bold", inherit.aes = FALSE)
 
```

```{r}
p
```


```{r}
ggsave(here("figures/Circular_terrestrial_transboundary_barplot.png"), dpi = 300, width = 15, height = 10)
```





























```{r}
# Create dataset

data<-iso3_df %>% 
  #filter(labels == "Transboundary") #%>% 
  mutate(Country = countrycode(ISO3, "iso3c", "country.name"),
        perc_trans = prop_trans*100,
         value = 100,
         perc_trans = ifelse(is.na(perc_trans) == T, 0, perc_trans)) %>% 
  rename(group = Continent,
         individual = Country,
         fill_val = perc_trans) %>% 
  dplyr::select(-n_basins, -n_trans, -prop_trans, -ISO3)

data<- data %>% arrange(group, fill_val)

# Set a number of 'empty bar' to add at the end of each group
empty_bar=3
to_add = data.frame( matrix(NA, empty_bar*length(unique(data$group)), ncol(data)) )
colnames(to_add) = colnames(data)
to_add$group=rep(levels(data$group), each=empty_bar)
data=rbind(data, to_add) %>% 
  mutate(value = ifelse(is.na(group) == T, 0, 100))
data=data %>% arrange(group)
data$id=seq(1, nrow(data))
 
# Get the name and the y position of each label
label_data=data
number_of_bar=nrow(label_data)
angle= 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust<-ifelse( angle < -90, 1, 0)
label_data$angle<-ifelse(angle < -90, angle+180, angle)
 
# prepare a data frame for base lines
base_data=data %>% 
  filter(!is.na(group) == T) %>% 
  group_by(group) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)),
         group = ifelse(group == "North America","North \nAmerica",
                        ifelse(group == "South America", "South \nAmerica", group))) 
 
# prepare a data frame for grid (scales)
grid_data = base_data
grid_data$end = grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start = grid_data$start - 1
grid_data=grid_data[-1,]
 

```

```{r}
# Make the plot
p = ggplot(data, aes(x=as.factor(id), y=value, fill = fill_val)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  geom_bar(aes(x=as.factor(id), y=value), stat="identity", alpha=0.5) +
   scale_fill_continuous(low="blue", high="red", limits=c(0,100)) +
  
  
  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
  # Add text showing the value of each 100/75/50/25 lines
  annotate("text", x = rep(max(data$id),5), y = c(20, 40, 60, 80, 100), label = c("20", "40", "60", "80", "100") , color="grey", size=3 , angle=0, fontface="bold", hjust=1) +
  
  geom_bar(aes(x=as.factor(id), y=value, fill=fill_val), stat="identity", alpha=0.5) +
  ylim(-100,120) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  coord_polar() + 
  geom_text(data=label_data, aes(x=id, y=value+10, label=individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) +
  
  # Add base line information
  geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
  geom_text(data=base_data, aes(x = title, y = -18, label=group), hjust=c(0.5,0.5,0.2,0.2,0.2,0), vjust = c(0,0,0,0,0,0),colour = "black", alpha=0.8, size=2, fontface="bold", inherit.aes = FALSE)
 
```



```{r}



# Set a number of 'empty bar' to add at the end of each group
empty_bar <- 2
nObsType <- nlevels(as.factor(data$observation))
to_add <- data.frame( matrix(NA, empty_bar*nlevels(data$group)*nObsType, ncol(data)) )
colnames(to_add) <- colnames(data)
to_add$group <- rep(levels(data$group), each=empty_bar*nObsType )
data <- rbind(data, to_add)
data <- data %>% arrange(group, individual)
data$id <- rep( seq(1, nrow(data)/nObsType) , each=nObsType)
 
# Get the name and the y position of each label
label_data <- data %>% group_by(id, individual) %>% summarize(tot=sum(value))
number_of_bar <- nrow(label_data)
angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust <- ifelse( angle < -90, 1, 0)
label_data$angle <- ifelse(angle < -90, angle+180, angle)
 
# prepare a data frame for base lines
base_data <- data %>% 
  group_by(group) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))
 
# prepare a data frame for grid (scales)
grid_data <- base_data
grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start <- grid_data$start - 1
grid_data <- grid_data[-1,]

```

```{r}
# Make the plot
p <- ggplot(data) +      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=value, fill=fill_val), stat="identity", alpha=0.5) +
  scale_fill_viridis(discrete=TRUE) +
  
  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 0, xend = start, yend = 0), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 50, xend = start, yend = 50), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 150, xend = start, yend = 150), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 200, xend = start, yend = 200), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
  # Add text showing the value of each 100/75/50/25 lines
  ggplot2::annotate("text", x = rep(max(data$id),5), y = c(0, 50, 100, 150, 200), label = c("0", "50", "100", "150", "200") , color="grey", size=6 , angle=0, fontface="bold", hjust=1) +
  
  ylim(-150,max(label_data$tot, na.rm=T)) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  coord_polar() +
  
  # Add labels on top of each bar
  geom_text(data=label_data, aes(x=id, y=tot+10, label=individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=5, angle= label_data$angle, inherit.aes = FALSE ) +
  
  # Add base line information
  geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
  geom_text(data=base_data, aes(x = title, y = -18, label=group), hjust=c(1,1,0,0, 0,0), vjust = c(0,0,0,0,0,-0.5), colour = "black", alpha=0.8, size=2, fontface="bold", inherit.aes = FALSE)
```

```{r}
p
```

