---
title: "Untitled"
author: "Caitie"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(data.table)
library(countrycode)
library(raster)
library(sf)
library(ggplot2)
library(ggrepel)
library(tmap)

t_crs<-'ESRI:54009'
```

# Basins

```{r}
basin_table<-read.csv(here("results/Basin_results_table.csv"))

trans_basins<-basin_table %>% 
  filter(n_iso3 >1)
```


```{r}
basins_area<-st_read(here("output_data/Basins/Basins_lv8_mainbasin_moll.shp")) %>% 
  st_make_valid() %>% 
  mutate(b_area_km2 = as.numeric(st_area(.))*1e-6) %>% 
  filter(MAIN_BAS %in% trans_basins$MAIN_BAS)
```

# Feasbility score


```{r}
test<-read.delim(here("raw_data/Mason_2020_management/Transboundary_data.txt"))

feas_shp<-st_read(here("raw_data/Mason_2020_management/Transboundary_data.gdb"), layer = "Global_Feas_10km") %>% 
  st_transform(., t_crs)

feas<-st_read(here("raw_data/Mason_2020_management/Transboundary_data.gdb"), layer = "Global_Feas_10km") %>% 
  as.data.frame() %>% 
  dplyr::select(-Shape) %>% 
  dplyr::select(pair, FI_10km) %>% 
  mutate(n_word = stringr::str_count(pair, '\\w+'))

feas1<-feas %>% 
  filter(n_word == 2) %>% 
  separate(pair, c('Country_x', 'Country_y'), remove = F) %>% 
  mutate(ISO3_x = countrycode(Country_x, "country.name", "iso3c"),
         ISO3_y = countrycode(Country_y, "country.name", "iso3c"),
         ISO3_x = ifelse(is.na(ISO3_x) == T, "XXK", ISO3_x),
         ISO3_y = ifelse(is.na(ISO3_y) == T, "XXK", ISO3_y))


feas2<- feas %>% 
  filter(n_word>2)

write.csv(feas2, here("output_data/Feasibility/Feasibility_pair_correction.csv"))

```

```{r}
feas2<-read.csv(here("output_data/Feasibility/Feasibility_pair_correction_CK.csv")) %>% 
  mutate(ISO3_x = countrycode(Country_x, "country.name", "iso3c"),
         ISO3_y = countrycode(Country_y, "country.name", "iso3c")) %>% 
  filter(!Country_y == "Saint-Martin") %>% 
  dplyr::select(-X)

which(is.na(feas2$ISO3_x) == T | is.na(feas2$ISO3_y) == T)

```

```{r}
all_feas<-rbind(feas1,feas2)
```

# Test with one country

```{r}
#test<-all_feas %>% 
#  filter(pair == "Argentina Chile")

#test_shp<-feas_shp %>% 
#  filter(pair == "Argentina Chile")
```

```{r}
#tmap_mode("view")

#tm_shape(test_shp) +
#  tm_lines(col = "FI_10km")
```

# Mean feasibility 

```{r}
feas_shp<-full_join(feas_shp, all_feas)

#mean_feas<-feas_shp %>% 
#  group_by(ISO3_x, ISO3_y, Country_x, Country_y, pair) %>% 
#  summarise(avg_feas = mean(FI_10km, na.rm = T))
```

# Intersect basins with feasibility

```{r}
basin_feas<-st_intersection(basins_area, feas_shp)

total_basin_area = sum(basins_area$b_area_km2,na.rm = T)

```

```{r}
mean_basin_feas<- basin_feas %>% 
  group_by(MAIN_BAS, b_area_km2) %>% 
  summarise(mean_feas = mean(FI_10km, na.rm = T))

# Look into why these are NAN
test<-mean_basin_feas %>% 
  filter(is.nan(mean_feas) == T)

test2<-basin_table %>% 
  filter(MAIN_BAS %in% test$MAIN_BAS)
```

Higher mean feasibility index = greater feasibility
Lower = less feasibility
```{r}
mean_basin_feas<-mean_basin_feas %>% 
  mutate(prop_basin_area = b_area_km2/total_basin_area,
    mean_feas_area = mean_feas/ b_area_km2,
    mean_feas_prop = mean_feas/prop_basin_area)

mean_basin_feas<-mean_basin_feas %>% 
  mutate(norm_feas_area = (mean_feas_area - min(mean_basin_feas$mean_feas_area, na.rm = T)) / (max(mean_basin_feas$mean_feas_area, na.rm = T) - min(mean_basin_feas$mean_feas_area, na.rm = T)),
         norm_feas_prop = (mean_feas_prop - min(mean_basin_feas$mean_feas_prop, na.rm = T)) / (max(mean_basin_feas$mean_feas_prop, na.rm = T) - min(mean_basin_feas$mean_feas_prop, na.rm = T)))
```

# Join to marine transboundary sediment data

```{r}
eez_mismatch<-read.csv(here("output_data/EEZ_sediments/EEZ_sed_trans_mismatch.csv")) %>% 
  group_by(MAIN_BAS) %>% 
  summarise(eez_sed = sum(total_eez_sed, na.rm = T),
            source_sed = sum(Source_sediment, na.rm = T))

```

```{r}
basin_sed_feas<-left_join(mean_basin_feas, eez_mismatch, by = "MAIN_BAS") %>% 
  dplyr::select(-geometry) %>% 
  as.data.frame() %>% 
  filter(!is.na(eez_sed) == T)
```

```{r}
sub<-basin_sed_feas %>% 
  filter(norm_feas_area <0.5)

ggplot(basin_sed_feas, aes(y = eez_sed/1000000, x = norm_feas_area)) +
  geom_point() +
  coord_trans("log10")+
  theme_bw()
```


Lots of NAs - basins in Australia, Oceania etc are not transboundary
