---
title: "Untitled"
author: "Caitie"
date: "2022-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(tmap)
library(sf)
library(patchwork)
library(rnaturalearth)
library(rnaturalearthdata)
library(circlize)
#devtools::install_github("https://github.com/mattflor/chorddiag")
library(chorddiag)
library(randomcoloR)
library(RColorBrewer)

t_crs<-'ESRI:54009'

```

## Continents data

```{r}
continents<-read.csv(here("raw_data/Countries_by_continent.csv")) %>% 
  dplyr::select(ISO3, Continent)
```

```{r}
eez_mismatch<-read.csv(here("output_data/EEZ_sediments/EEZ_sed_trans_mismatch.csv"))

test<-eez_mismatch %>% 
  filter(Source_ISO3 == Sink_ISO3)
```

Mismatch between country that produces majority of sediment and where sediment is released
```{r}
sub_mismatch<-eez_mismatch %>% 
  filter(!prop_sed == 0) %>% 
  full_join(., continents, by = c("Source_ISO3" = "ISO3")) %>% 
  rename(Source_continent = Continent) %>% 
  full_join(., continents, by = c("Sink_ISO3" = "ISO3")) %>% 
  rename(Sink_continent = Continent)

length(unique(sub_mismatch$MAIN_BAS))
```



```{r}
africa<-sub_mismatch %>% 
  filter(Source_continent == "Africa",
         Sink_continent == "Africa") %>% 
  dplyr::select(Source_ISO3, Sink_ISO3, MAIN_BAS,total_eez_sed) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (total_eez_sed)/1000000) %>% 
  filter(sed_mt>0) %>% 
  group_by(Source_ISO3, Sink_ISO3) %>% 
  summarise(sed_mt = sum(sed_mt, na.rm = T))



#length(unique(africa$MAIN_BAS))

asia<-sub_mismatch %>% 
  filter(Source_continent == "Asia",
         Sink_continent == "Asia") %>% 
  dplyr::select(Source_ISO3, Sink_ISO3, MAIN_BAS,total_eez_sed) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (total_eez_sed)/1000000) %>% 
  filter(sed_mt>0) %>% 
  group_by(Source_ISO3, Sink_ISO3) %>% 
  summarise(sed_mt = sum(sed_mt, na.rm = T))

europe<-sub_mismatch %>% 
  filter(Source_continent == "Europe",
         Sink_continent == "Europe") %>% 
  dplyr::select(Source_ISO3, Sink_ISO3, MAIN_BAS,total_eez_sed) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (total_eez_sed)/1000000) %>% 
  filter(sed_mt>0) %>% 
  group_by(Source_ISO3, Sink_ISO3) %>% 
  summarise(sed_mt = sum(sed_mt, na.rm = T))

#length(unique(europe$MAIN_BAS))

na<-sub_mismatch %>% 
  filter(Source_continent == "North America",
         Sink_continent == "North America") %>% 
  dplyr::select(Source_ISO3, Sink_ISO3, MAIN_BAS,total_eez_sed) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (total_eez_sed)/1000000) %>% 
  filter(sed_mt>0) %>% 
  group_by(Source_ISO3, Sink_ISO3) %>% 
  summarise(sed_mt = sum(sed_mt, na.rm = T))

#length(unique(na$MAIN_BAS))

sa<-sub_mismatch %>% 
  filter(Source_continent == "South America",
         Sink_continent == "South America") %>% 
  dplyr::select(Source_ISO3, Sink_ISO3, MAIN_BAS,total_eez_sed) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (total_eez_sed)/1000000) %>% 
  filter(sed_mt>0) %>% 
  group_by(Source_ISO3, Sink_ISO3) %>% 
  summarise(sed_mt = sum(sed_mt, na.rm = T))
#length(unique(sa$MAIN_BAS))

oceania<-sub_mismatch %>% 
  filter(Source_continent == "Oceania",
         Sink_continent == "Oceania") %>% 
  dplyr::select(Source_ISO3, Sink_ISO3, MAIN_BAS,total_eez_sed) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (total_eez_sed)/1000000) %>% 
  filter(sed_mt>0) %>% 
  group_by(Source_ISO3, Sink_ISO3) %>% 
  summarise(sed_mt = sum(sed_mt, na.rm = T))
#length(unique(sa$MAIN_BAS))

cross<-sub_mismatch %>% 
  filter(Source_continent != Sink_continent) %>% 
  dplyr::select(Source_ISO3, Sink_ISO3, MAIN_BAS,total_eez_sed) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (total_eez_sed)/1000000) %>% 
  filter(sed_mt>0) %>% 
  group_by(Source_ISO3, Sink_ISO3) %>% 
  summarise(sed_mt = sum(sed_mt, na.rm = T))
#length(unique(sa$MAIN_BAS))
```

```{r}
pal <- brewer.pal(9, "YlGnBu")
```

# Africa

```{r}
png(here("figures/Chord_diagram_Africa_mismatch.png"), width = 5, height = 5, units = "in", res = 300)

par(cex = 1, mar = c(0, 0, 0, 0))

circos.par(gap.after = 8,
           start.degree = 85, 
           clock.wise = FALSE)

chordDiagram(africa,grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             preAllocateTracks = 1,
             annotationTrack = "grid",
             link.border = "darkgray",
             diffHeight = mm_h(3.5)) 

circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .3, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.length = 0.5, sector.index = sector.name, track.index = 2)
}, bg.border = NA) 


circos.clear()

dev.off()
```



# Asia
```{r}
png(here("figures/Chord_diagram_Asia_mismatch.png"), width = 5, height = 5, units = "in", res = 300)

par(cex = 1, mar = c(0, 0, 0, 0))

circos.par(gap.after = 8,
           start.degree = 85, 
           clock.wise = FALSE)

chordDiagram(asia,grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             preAllocateTracks = 1,
             annotationTrack = "grid",
             link.border = "darkgray",
             diffHeight = mm_h(3.5)) 

circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .3, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.length = 0.5, sector.index = sector.name, track.index = 2)
}, bg.border = NA) 


circos.clear()

dev.off()
```

# Europe
```{r}
png(here("figures/Chord_diagram_Europe_mismatch.png"), width = 5, height = 5, units = "in", res = 300)

par(cex = 1, mar = c(0, 0, 0, 0))

circos.par(gap.after = 8,
           start.degree = 85, 
           clock.wise = FALSE)

chordDiagram(europe,grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             preAllocateTracks = 1,
             annotationTrack = "grid",
             link.border = "darkgray",
             diffHeight = mm_h(3.5)) 

circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .3, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.length = 0.5, sector.index = sector.name, track.index = 2)
}, bg.border = NA) 


circos.clear()


dev.off()
```

# North America
```{r}
png(here("figures/Chord_diagram_North_America_mismatch.png"), width = 5, height = 5, units = "in", res = 300)

par(cex = 1, mar = c(0, 0, 0, 0))

circos.par(gap.after = 8,
           start.degree = 85, 
           clock.wise = FALSE)

chordDiagram(na,grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             preAllocateTracks = 1,
             annotationTrack = "grid",
             link.border = "darkgray",
             diffHeight = mm_h(3.5)) 

circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .3, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.length = 0.5, sector.index = sector.name, track.index = 2)
}, bg.border = NA) 


circos.clear()


dev.off()
```

# South America
```{r}
png(here("figures/Chord_diagram_South_America_mismatch.png"), width = 5, height = 5, units = "in", res = 300)

par(cex = 1, mar = c(0, 0, 0, 0))

circos.par(gap.after = 8,
           start.degree = 85, 
           clock.wise = FALSE)

chordDiagram(sa,grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             preAllocateTracks = 1,
             annotationTrack = "grid",
             link.border = "darkgray",
             diffHeight = mm_h(3.5)) 

circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .3, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.length = 0.5, sector.index = sector.name, track.index = 2)
}, bg.border = NA) 


circos.clear()


dev.off()
```

# Oceania - no data


# Cross

```{r}
png(here("figures/Chord_diagram_Cross_Continent_mismatch.png"), width = 5, height = 5, units = "in", res = 300)

par(cex = 1, mar = c(0, 0, 0, 0))

circos.par(gap.after = 8,
           start.degree = 85, 
           clock.wise = FALSE)

chordDiagram(cross,grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             preAllocateTracks = 1,
             annotationTrack = "grid",
             link.border = "darkgray",
             diffHeight = mm_h(3.5)) 

circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .3, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.length = 0.5, sector.index = sector.name, track.index = 2)
}, bg.border = NA) 


circos.clear()


dev.off()
```

