---
title: "Untitled"
author: "Caitie"
date: '2022-07-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(sf)
library(countrycode)

t_crs<-'ESRI:54009'

options(dplyr.summarise.inform = FALSE)
options(scipen = 999)
```
# Load data 

## EEZ names

```{r}
eez<-read.csv(here("output_data/EEZ_sediments/eez_v11.csv")) %>% 
  dplyr::select(MRGID_TER1, ISO_TER1, ISO_SOV1)
```


## Pourpoints locations

```{r}
pp_loc_list<-list.files(here("output_data/Pourpoints"), pattern = "Missing_pp_chunk", full.names = T)

pp_loc_mis<-
  do.call(rbind,
          lapply(pp_loc_list, read.csv))

pp_all<-read.csv(here("output_data/Pourpoints/PP_location_all.csv"))

pp_done<-rbind(pp_all, pp_loc_mis) 
```

```{r}
riv_bas<-st_read(here("output_data/Sediment_at_pourpoint/Sediment_at_pourpoint.gpkg")) %>% 
  dplyr::select(MAIN_RI, MAIN_BAS) %>% 
  as.data.frame() %>% 
  dplyr::select(-geom) %>% 
  unique()

```

# Match EEZ to Country to get sink country

```{r}
final_shared<-read.csv(here("output_data/EEZ_sediments/pour_points_shared_eez.csv")) %>% 
  full_join(., eez, by = c("EEZ" = "MRGID_TER1", "ISO_SOV1")) %>% 
  rename(Sink_ISO3 = ISO_TER1,
         Sink_name = GEONAME,
         Sink_SOVISO3 = ISO_SOV1,
         Source_ISO3 = ISO3,
         Source_name = Country_pp,
         sediment_eez = sediment_EEZ,
         Source_sediment = sed_pp) %>% 
  mutate(sediment_eez2 = ifelse(sediment_eez>Source_sediment, Source_sediment, sediment_eez),
         prop_sed = sediment_eez/Source_sediment,
         Sink_ISO3 = ifelse(Sink_ISO3 == " ", Sink_SOVISO3, Sink_ISO3)) %>% 
  left_join(., riv_bas)
```

```{r}
MB<-unique(final_shared$MAIN_BAS)

eez_mismatch<-c()

for(k in 1:length(MB)){
print(k)
 sub_shared<-final_shared %>% 
  filter(MAIN_BAS == MB[k],
         !is.na(sediment_eez) == T) 
 
 source_sediment = sub_shared %>% 
   dplyr::select(Source_sediment, MAIN_RI) %>% 
   unique()
 
 total_source_sediment<-sum(source_sediment$Source_sediment, na.rm = T)

  prop_shared <- sub_shared %>% 
    group_by(MAIN_BAS, Source_ISO3, Sink_ISO3) %>% 
    summarise(total_eez_sed = sum(sediment_eez2, na.rm = T)) %>% 
    mutate(Source_sediment = round(total_source_sediment, 1),
           prop_sed = total_eez_sed/Source_sediment) %>% 
    filter(!Source_ISO3 == Sink_ISO3)
  
  eez_mismatch<-rbind(eez_mismatch, prop_shared)
}
```

```{r}
write.csv(eez_mismatch, here("output_data/EEZ_sediments/EEZ_sed_trans_mismatch.csv"))
```

Think through what we want the proportions to tell us

1. From Basin 1 X% of sediment starts in Spain but ends up in France
2. Of all the sediment transport from Spain, Y% ends up in France
3. How many countries have transboundary transport
4. How many tonnes are transboundary?
