---
title: "Untitled"
author: "Caitie"
date: "19/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(data.table)
library(countrycode)
library(raster)
```

# How many watersheds are transboundary globally?

```{r}
list_prop_basin<-list.files(here("output_data"), pattern = "Prop_basin_iso3", full.names = TRUE)

sub_prop_basin<-list_prop_basin[grep(list_prop_basin, pattern = ".csv")] 

dat <- 
  do.call(rbind,
          lapply(sub_prop_basin, read.csv))

```

```{r}
#Count number of countries in each watershed
iso3_basins<-dat %>% 
  group_by(MAIN_BAS) %>% 
  summarise(n_iso3 = length(unique(ISO3))) 
```

# Number of watersheds/countries

```{r}
# How many basins were assessed
length(unique(iso3_basins$MAIN_BAS))

# How many are transboundary
length(which(iso3_basins$n_iso3>1))

trans_basins<-iso3_basins %>% 
  filter(n_iso3 >1)

# Proportion of transboundary
length(which(iso3_basins$n_iso3>1))/length(unique(iso3_basins$MAIN_BAS))
```


```{r}
#Transboundary by continent
cont_basins<-dat %>% 
  group_by(Continent) %>% 
  summarise(n_basins = length(unique(MAIN_BAS)))

cont_trans_basins<-dat %>% 
  filter(MAIN_BAS %in% trans_basins$MAIN_BAS) %>% 
  group_by(Continent) %>% 
  summarise(n_trans = length(unique(MAIN_BAS)))

cont<-full_join(cont_basins, cont_trans_basins) %>% 
  mutate(prop_trans = n_trans/n_basins)

cont
```



```{r}
iso3_cont_basins<-dat %>% 
  group_by(ISO3, Continent) %>% 
  summarise(n_basins = length(unique(MAIN_BAS)))

iso3_trans_basins<-dat %>% 
  filter(MAIN_BAS %in% trans_basins$MAIN_BAS) %>% 
  group_by(ISO3, Continent) %>% 
  summarise(n_trans = length(unique(MAIN_BAS)))

iso3_df<-full_join(iso3_cont_basins, iso3_trans_basins) %>% 
  mutate(prop_trans = n_trans/n_basins,
         Country = countrycode(ISO3, "iso3c", "country.name"))
```

```{r}
# Number of countries in analysis
length(unique(iso3_df$ISO3))

# Number of countries with more than 1 basin
length(which(iso3_df$n_basins>1))

# Number of countries with transboundary basins
length(which(iso3_df$n_trans>0))
```

# Sediment export

```{r}
# Total sediment exported
#sed_moll<-raster(here("raw_data/Sediment/sediment_export_global_moll.tif"))

#total_sed<-cellStats(sed_moll, "sum")

total_sed<-24849341974

# unit is tonnes/ha/yr
#1 Mt = 1000000 t

#Estimated ha of global basins = 13511831300

total_sed_mt<-total_sed/1000000 #Megaton

total_sed_mt
```

# Sediment from all transboundary basins

```{r}
list_sed_basin<-list.files(here("output_data/Sediment"), pattern = ".shp", full.names = T)

#list_sed_basin<-list.files(here("output_data/Transboundary"), pattern = #"Terrestrial_transboundary_", full.names = TRUE)

sed_dat <- 
  do.call(rbind,
          lapply(list_sed_basin, st_read))

sub_dat<-dat %>% 
  dplyr::select(MAIN_BAS, n)

sed_dat2<-sed_dat %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  full_join(., sub_dat) %>% 
  filter(n>1)

trans_sed_sum<-sed_dat2 %>% 
  group_by(ISO3, Continent, MAIN_BAS) %>% 
  filter(!duplicated(sed_sum))

```

```{r}
# Total sediment export? What does this layer represent?
sum(trans_sed_sum$sed_sum, na.rm = T)/1000000 #Megaton

# Proportion of transboundary sed
sum(trans_sed_sum$sed_sum)/total_sed

# Number of basins
length(unique(sed_dat$MAIN_BAS))
```

# Transboundary, cryptoheric watersheds

```{r}
list_crypt_sed_basin<-list.files(here("output_data/Transboundary"), pattern = "Terrestrial_transboundary_", full.names = TRUE)

crypt_sed_dat <- 
  do.call(rbind,
          lapply(list_crypt_sed_basin, read.csv))

trans_crypt_sed_sum<-crypt_sed_dat %>% 
  group_by(ISO3, Continent, MAIN_BAS) %>% 
  filter(!duplicated(sed_sum))
```

```{r}
#Number of transboundary cryptoheric basins

length(unique(trans_crypt_sed_sum$MAIN_BAS))

# Proportion of transboundary that are also cryptoheric
length(unique(trans_crypt_sed_sum$MAIN_BAS))/length(which(iso3_basins$n_iso3>1))

# Breakdown by Continent
sub<-trans_crypt_sed_sum %>% 
  ungroup() %>% 
  dplyr::select(MAIN_BAS, Continent) %>% 
  filter(!duplicated(MAIN_BAS))

table(sub$Continent)/length(unique(trans_crypt_sed_sum$MAIN_BAS))

```
```{r}
# Total sediment export? What does this layer represent?
sum(trans_crypt_sed_sum$sed_sum, na.rm = T)/1000000 #Megaton

# Proportion of transboundary sed
sum(trans_crypt_sed_sum$sed_sum)/total_sed

```

```{r}
iso3_crypt_trans_basins<- trans_crypt_sed_sum %>% 
  group_by(ISO3, Continent) %>% 
  summarise(n_crypt_basins = length(unique(MAIN_BAS)))

iso3_df<-full_join(iso3_cont_basins, iso3_trans_basins) %>%
  full_join(., iso3_crypt_trans_basins) %>% 
  mutate(prop_trans = n_trans/n_basins,
         prop_crypt = n_crypt_basins/n_basins,
         prop_trans_crypt = n_crypt_basins/n_trans,
         Country = countrycode(ISO3, "iso3c", "country.name"))
```


```{r}
sub_sed_dat<-crypt_sed_dat %>% 
  filter(pp_iso3 != max_sed_iso3)

test<-sub_sed_dat %>% 
  filter(pp_iso3 %in% c("c(\"GIN\", \"SLE\")", "c(\"GMB\", \"SEN\")",  "c(\"IRN\", \"PAK\")", "c(\"IDN\", \"MYS\")", "c(\"CRI\", \"NIC\")", "c(\"PRI\", \"VIR\")", "c(\"BRA\", \"URY\")", "c(\"CHL\", \"PER\")"))

sub_sed_dat2<-sub_sed_dat %>% 
  filter(!pp_iso3 %in% c("c(\"GIN\", \"SLE\")", "c(\"GMB\", \"SEN\")",  "c(\"IRN\", \"PAK\")", "c(\"IDN\", \"MYS\")", "c(\"CRI\", \"NIC\")", "c(\"PRI\", \"VIR\")", "c(\"BRA\", \"URY\")", "c(\"CHL\", \"PER\")"))

# Main basins with mismatch between country with max sediment export and country with pourpoint
length(unique(sub_sed_dat2$MAIN_BAS))

# Watersheds with equal proportion of pourpoints
length(unique(test$MAIN_BAS))
```

```{r}
# Basins where >90% of sediment is produced in a different country than the pourpoint
prop_sed<-sub_sed_dat2 %>% 
  filter(prop_sed>0.9)

length(unique(prop_sed$MAIN_BAS))
```


```{r}
table(test$Continent)/length(unique(sub_sed_dat2$MAIN_BAS))
```

# Transboundary coral reef sediments

```{r}
reef_pp<-st_read(here("raw_data/Pourpoints/pour_points_all.shp")) 

reef_sed<- trans_crypt_sed_sum %>% 
  filter(HYRIV_I %in% reef_pp$HYRIV_I)
```

```{r}
length(unique(reef_sed$MAIN_BAS))
```

```{r}
sum(reef_sed$sed_sum, na.rm = T)/sum(trans_crypt_sed_sum$sed_sum, na.rm = T)

sum(reef_sed$sed_sum, na.rm = T)/sum(trans_sed_sum$sed_sum, na.rm = T)

sum(reef_sed$sed_sum, na.rm = T)/total_sed
```

