---
title: "Untitled"
author: "Caitie"
date: "09/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(tmap)
library(sf)
library(patchwork)
library(rnaturalearth)
library(rnaturalearthdata)
library(circlize)
#devtools::install_github("https://github.com/mattflor/chorddiag")
library(chorddiag)
library(randomcoloR)
library(RColorBrewer)

t_crs<-'ESRI:54009'

```

# Terrestrial mismatch plot

## Continents data

```{r}
continents<-read.csv(here("raw_data/Countries_by_continent.csv"))
```


Mismatch in where the sediment comes form and where the pourpoint is

At this point we don't care whether it is cryptoheric or not

```{r}
list_mismatch<-list.files(here("output_data/Transboundary"), pattern = "Terrestrial", full.names = T)
  
mismatch<-do.call(rbind,
          lapply(list_mismatch, read.csv))

```

Mismatch between country that produces majority of sediment and where sediment is released
```{r}
sub_mismatch<-mismatch %>% 
  filter(!pp_iso3 == "character(0)",
    max_sed_iso3 != pp_iso3,
          nchar(pp_iso3)==3,
    !prop_sed == 0)

length(unique(sub_mismatch$MAIN_BAS))
```

```{r}
lty_df = data.frame(c("S1", "S2", "S3"), c("E5", "E6", "E4"), c(1, 2, 3))

chordDiagram(mat, grid.col = grid.col, link.lty = lty_df, link.lwd = lwd_df,
    link.border = border_df)
```

```{r}
africa<-sub_mismatch %>% 
  filter(Continent == "Africa",
         !pp_iso3 == max_sed_iso3,
         !is.na(pp_dis) == T) %>% 
  dplyr::select(ISO3, MAIN_BAS,pp_iso3, max_sed_iso3, pp_dis) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (pp_dis)/1000000) %>% 
  filter(sed_mt>0) 

africa_plot_dat<- africa %>% 
  dplyr::select(ISO3, pp_iso3, ISO3, sed_mt) %>% 
  rename(from = ISO3,
         to = pp_iso3,
         value = sed_mt) %>% 
  group_by(from, to) %>% 
  summarise(value = sum(value, na.rm = T)) %>% 
  filter(value >0.1)

africa_lwd_df = data.frame(c("S1", "S2", "S3"), c("E5", "E6", "E4"), c(2, 2, 2))
africa_border_df = data.frame(c("S1", "S2", "S3"), c("E5", "E6", "E4"), c(1, 1, 1))


#length(unique(africa$MAIN_BAS))

asia<-sub_mismatch %>% 
  filter(Continent == "Asia",
         !ISO3 == pp_iso3,
         !pp_iso3 == max_sed_iso3,
         !is.na(pp_dis) == T) %>% 
  dplyr::select(ISO3, MAIN_BAS,pp_iso3, max_sed_iso3, pp_dis) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (pp_dis)/1000000)  %>% 
  dplyr::select(ISO3, pp_iso3, max_sed_iso3, sed_mt) %>% 
  rename(from = ISO3,
         to = pp_iso3,
         value = sed_mt) %>% 
  group_by(from, to) %>% 
  summarise(value = sum(value, na.rm = T))%>% 
  filter(value >0.1)

#length(unique(asia$MAIN_BAS))

europe<-sub_mismatch %>% 
  filter(Continent == "Europe",
         !ISO3 == pp_iso3,
         !pp_iso3 == max_sed_iso3,
         !is.na(pp_dis) == T) %>% 
  dplyr::select(ISO3, MAIN_BAS,pp_iso3, max_sed_iso3, pp_dis) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (pp_dis)/1000000)  %>% 
  dplyr::select(ISO3, pp_iso3, max_sed_iso3, sed_mt) %>% 
  rename(from = ISO3,
         to = pp_iso3,
         value = sed_mt) %>% 
  group_by(from, to) %>% 
  summarise(value = sum(value, na.rm = T))%>% 
  filter(value >0.1)

#length(unique(europe$MAIN_BAS))

na<-sub_mismatch %>% 
  filter(Continent == "North America",
         !ISO3 == pp_iso3,
         !pp_iso3 == max_sed_iso3,
         !is.na(pp_dis) == T) %>% 
  dplyr::select(ISO3, MAIN_BAS,pp_iso3, max_sed_iso3, pp_dis) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (pp_dis)/1000000)  %>% 
  dplyr::select(ISO3, pp_iso3, max_sed_iso3, sed_mt) %>% 
  rename(from = ISO3,
         to = pp_iso3,
         value = sed_mt) %>% 
  group_by(from, to) %>% 
  summarise(value = sum(value, na.rm = T))%>% 
  filter(value >0.1)

#length(unique(na$MAIN_BAS))

sa<-sub_mismatch %>% 
  filter(Continent == "South America",
         !ISO3 == pp_iso3,
         !pp_iso3 == max_sed_iso3,
         !is.na(pp_dis) == T) %>% 
  dplyr::select(ISO3, MAIN_BAS,pp_iso3, max_sed_iso3, pp_dis) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (pp_dis)/1000000)  %>% 
  dplyr::select(ISO3, pp_iso3, max_sed_iso3, sed_mt) %>% 
  rename(from = ISO3,
         to = pp_iso3,
         value = sed_mt) %>% 
  group_by(from, to) %>% 
  summarise(value = sum(value, na.rm = T)) %>% 
  filter(value >0.1)

#length(unique(sa$MAIN_BAS))
```
# Africa
```{r}
#png(here("figures/Chord_diagram_Africa_mismatch.png"))
pal <- brewer.pal(9, "YlGnBu")

circos.par(gap.after = 6,
           start.degree = 85, 
           clock.wise = FALSE,
           circle.margin = 0.05)

chordDiagram(africa,  grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             annotationTrack = "grid", preAllocateTracks = 1,
             link.border = "darkgray",
             diffHeight = mm_h(3.5))
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .25, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.7))
  circos.axis(h = "top", labels.cex = 0.01, sector.index = sector.name, track.index = 2)
}, bg.border = NA) +
  title("Africa")

circos.clear()

#dev.off()
```
# Asia
```{r}
png(here("figures/Chord_diagram_Asia_mismatch.png"))
pal <- brewer.pal(9, "YlGnBu")

circos.par(gap.after = 6,
           start.degree = 85, 
           clock.wise = FALSE,
           circle.margin = 0.05)

chordDiagram(asia,  grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             annotationTrack = "grid", preAllocateTracks = 1,
             link.border = "darkgray",
             diffHeight = mm_h(3.5))
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .25, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.7))
  circos.axis(h = "top", labels.cex = 0.01, sector.index = sector.name, track.index = 2)
}, bg.border = NA) +
  title("Asia")

circos.clear()

dev.off()
```

# Europe

```{r}
png(here("figures/Chord_diagram_Europe_mismatch.png"))

circos.par(gap.after = 6,
           start.degree = 85, 
           clock.wise = FALSE,
           circle.margin = 0.05)

chordDiagram(europe,  grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             annotationTrack = "grid", preAllocateTracks = 1,
             link.border = "darkgray",
             diffHeight = mm_h(3.5))
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .25, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.7))
  circos.axis(h = "top", labels.cex = 0.01, sector.index = sector.name, track.index = 2)
}, bg.border = NA) +
  title("Europe")

circos.clear()

dev.off()
```


# North America
```{r}
png(here("figures/Chord_diagram_North_America_mismatch.png"))
pal <- brewer.pal(9, "YlGnBu")

circos.par(gap.after = 6,
           start.degree = 85, 
           clock.wise = FALSE,
           circle.margin = 0.05)

chordDiagram(na,  grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             annotationTrack = "grid", preAllocateTracks = 1,
             link.border = "darkgray",
             diffHeight = mm_h(3.5))
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .25, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.7))
  circos.axis(h = "top", labels.cex = 0.01, sector.index = sector.name, track.index = 2)
}, bg.border = NA) +
  title("North America")

circos.clear()

dev.off()
```

# South America

```{r}
png(here("figures/Chord_diagram_South_America_mismatch.png"))
circos.par(gap.after = 6,
           start.degree = 85, 
           clock.wise = FALSE,
           circle.margin = 0.05)

chordDiagram(sa,  grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             annotationTrack = "grid", preAllocateTracks = 1,
             link.border = "darkgray",
             diffHeight = mm_h(3.5))
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .25, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.7))
  circos.axis(h = "top", labels.cex = 0.01, sector.index = sector.name, track.index = 2)
}, bg.border = NA) +
  title("South America")

circos.clear()

dev.off()
```

# Cross continent

```{r}
mis_cont<-sub_mismatch %>% 
    filter(!ISO3 == pp_iso3,
         !is.na(pp_dis) == T) %>% 
  dplyr::select(ISO3, MAIN_BAS,pp_iso3, max_sed_iso3, pp_dis) %>% #pp_dis is pourpoint discharge from each country
  mutate(sed_mt = (pp_dis)/1000000) %>% 
  filter(sed_mt>0) %>% 
  dplyr::select(pp_iso3, max_sed_iso3, sed_mt) %>% 
  rename(from = max_sed_iso3,
         to = pp_iso3,
         value = sed_mt) %>% 
  group_by(from, to) %>% 
  summarise(value = sum(value, na.rm = T))

mis_cont2<- mis_cont %>% 
  left_join(., continents, by = c("from" = "ISO3")) %>% 
  rename(from_Continent = Continent) %>% 
  dplyr::select(from, to, value, from_Continent) %>% 
  left_join(., continents, by = c("to" = "ISO3")) %>% 
  rename(to_Continent = Continent) %>% 
  dplyr::select(from, to, value, from_Continent, to_Continent) 

mis_cont3<- mis_cont2%>% 
  filter(from_Continent != to_Continent)

```


```{r}
png(here("figures/Chord_diagram_cross_continent_mismatch.png"))
circos.par(gap.after = 6,
           start.degree = 85, 
           clock.wise = FALSE,
           circle.margin = 0.05)

chordDiagram(sa,  grid.col = "gray", col = pal, transparency = 0.2, directional = 1,
             annotationTrack = "grid", preAllocateTracks = 1,
             link.border = "darkgray",
             diffHeight = mm_h(3.5))
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .25, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.7))
  circos.axis(h = "top", labels.cex = 0.01, sector.index = sector.name, track.index = 2)
}, bg.border = NA) +
  title("South America")

circos.clear()

dev.off()
```

